Feat/add limited trust
solo-io/gloo-mesh pull request #1084
Opened 2020-11-16 16:41 UTC by mihmatache

Implement limited trust in `gloo-mesh`.

The scope is to enable cross cluster communication via Istio without changing the root trust domain in each cluster. This will allow each mesh to configure its own security, and we will provide another security domain for the inter cluster communication.

In order to switch from using the shared trust model to the limited trust model you need to apply the following configuration change:
```diff
  apiVersion: networking.mesh.gloo.solo.io/v1alpha2
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
 spec:
   mtlsConfig:
-     autoRestartPods: true
+    autoRestartPods: false
-    shared:
+    limited:
       rootCertificateAuthority:
         generated: {}
   federation: {}
   meshes:
   - name: istiod-istio-system-mgmt-cluster
     namespace: service-mesh-hub
   - name: istiod-istio-system-remote-cluster
     namespace: service-mesh-hub
```

The existing shared trust certificate logic will generate the certificates for the inter cluster trust domain.

**Current limitations**:
- Only works correctly if the remote service exposes only 1 port, as from my research, Istio does not currently support sending packets to the same host on different ports through the egress gateway (https://github.com/istio/istio/issues/26689).
- Traffic shifting does not currently work with the limited trust limitations.

resolves #910

2020-11-17 16:28 UTC, joekelley commented
@mihmatache thanks for this PR! Could you add an e2e test to validate the new functionality?

2020-11-18 10:30 UTC, mihmatache commented
> @mihmatache thanks for this PR! Could you add an e2e test to validate the new functionality?

@joekelley I would be very happy to add an e2e test, but first I would like some feedback on the general approach as a confirmation. If I can get that, I will be glad to add the e2e test. Also, I am unable to add `work in progress` labels, as I do not have permission. Can you help with that?

2020-11-18 18:43 UTC, ilackarms requested changes
overall i like the approach you've taken here and this PR does an excellent job following established conventions and patterns we use elsewhere in SMH/gloo mesh. i think it would be helpful to set up a time to go over the design from a high level to confirm that this approach fulfills the overall vision for limited trust. cc @joekelley wrt setting something up

2020-11-18 18:43 UTC, ilackarms commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +}
it seems there is a bit of shared logic here between limited and shared trust (e.g. construction of  service entries, similar ingress gateways). i'd propose we refactor a function out of both to allow sharing some of the now-duplicated logic (with parameters for use where they differ)

2020-11-19 08:49 UTC, mimatache commented
> overall i like the approach you've taken here and this PR does an excellent job following established conventions and patterns we use elsewhere in SMH/gloo mesh. i think it would be helpful to set up a time to go over the design from a high level to confirm that this approach fulfills the overall vision for limited trust. cc @joekelley wrt setting something up

I would be very happy if we could set something up to talk :) I also have some remarks to make about the general design and would be curios about your take on these. You can find me on the solo slack if you want to set up something.

2020-11-19 09:03 UTC, mimatache commented on pkg/mesh-networking/translation/istio/traffictarget/istio_traffic_target_translator.go
> +	if t.isIstioInternalTarget(t.ctx, trafficTarget) {
There are 2 reasons for this:
1. Allowing istio internal services (istiod, ingress and egress gateways) would mean that, at least, for the egress gateway, would generate rules for the egress gateway that don't follow the same rules, and that might cause situations which are not clearly defined.
2. I can't think of any situation in which, when having replicated control plane for Istio (as both limited and shared trust use replicated control), where a user will be interested in calling the remote Istio control plane. In my opinion this will only cause the creation of entities that clutter the generated configurations.

2020-11-19 09:38 UTC, mimatache commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +	filterPatchOp := networkingv1alpha3spec.EnvoyFilter_Patch_INSERT_AFTER
At some point I wanted to use the envoy filter for limited trust as well, and was planning to use those variables for creating the filter. That plan went out the door when we found some issues with that approach, and I forgot to remove them. I will remove them now.

2020-11-19 10:58 UTC, mimatache commented on pkg/mesh-networking/translation/istio/mesh/mtls/mtls_translator.go
> +			Name:      fmt.Sprintf("%s-%s", virtualMeshRef.Name, defaultGatewayCredentialNameSuffix),
I would be more than happy to create some functions that can be used across translators, but I'm not sure where to put them. Also, keep in mind that some of these potential functions will probably be needed in adding traffic shift as well. Maybe we can take this subject up if we have a call to go over the approach

2020-11-20 16:21 UTC, ilackarms commented on pkg/certificates/agent/reconciliation/cert_agent_reconciler.go
> +			}
i think we should be able to revert this and use the existing issued certificate workflow to issue the gateway certificate

2020-12-09 09:33 UTC, mihmatache commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +		if _, ok := trafficTarget.Spec.GetKubeService().GetLabels()["istio"]; ok {
There are 2 reasons:
1. There is a chance it would create conflicting rules for services, as we would have multiple types of destination rules.
1. As a general concept, I believe we shouldn't be exposing mesh internal services inside the remote mesh. Only gloo mesh should know about them and use them accordingly.

2020-12-09 09:37 UTC, mihmatache commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +									Gateways: []string{"mesh"},
We are using it as a gateway for the next hop. We followed the model provided [here](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/) in order to implement this.

2020-12-09 10:40 UTC, mihmatache commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +}
While there is some shared logic, there is not that much, for instance for the gateway, only the object meta is the same. 
Also, most of the logic is about populating a struct, and whatever is not that, should be extracted outside those functions.
This, in my opinion would only make the code harder to read without actually giving us a lot of benefit.

2020-12-09 10:43 UTC, mihmatache commented on pkg/certificates/agent/reconciliation/cert_agent_reconciler.go
> +			}
I have updated the certificate logic. 
I moved this logic to the `REQUESTED` state, and updated the `mtls_translator.go` to pass the correct name for limited trust for the certificate. 
The certificate provided by default by SMH was not correct, since it was an intermediate certificate used for signing and the egress did not accept it as valid.

2020-12-10 09:54 UTC, mihmatache commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +										Host:   fmt.Sprintf("%s.%s.svc.cluster.local", egressGateway.Name, clientIstio.Installation.Namespace),
We don't actually have a service reference here, so I couldn't use the `ClusterDomainRegistry`

2020-12-21 21:16 UTC, ilackarms commented
/test

2020-12-21 23:07 UTC, ilackarms commented on .github/workflows/pull_request.yaml
> +      matrix:
we can expand the `matrix` used by the existing e2e istio job; let's try to reuse that if we can

2021-02-02 17:10 UTC, ilackarms commented on pkg/certificates/agent/reconciliation/cert_agent_reconciler.go
> +	contextutils.LoggerFrom(r.ctx).Infof("%v", issuedCertificate.Spec.TlsType)
improve log message + move to debug

2021-02-03 13:26 UTC, mihmatache commented on pkg/certificates/agent/reconciliation/cert_agent_reconciler.go
> +func generateSecretForLimitedTrust(issuedCertificate *v1alpha2.IssuedCertificate, issuedCertificateData secrets.IntermediateCAData) (*corev1.Secret, error) {
No the current certificate and secret is build as a signing certificate (which does not work for mTLS), thus we use it to sign the end certificate.

2021-02-03 13:29 UTC, mihmatache commented on ci/setup-gloomesh.sh
> -  --register \
The cli register function was not using the local charts to build the agent, but rather a prebuilt one, which resulted in not having the modified agent in the deployment.

2021-02-05 15:12 UTC, harveyxia commented on pkg/certificates/agent/reconciliation/cert_agent_reconciler.go
> +func generateSecretForLimitedTrust(issuedCertificate *v1alpha2.IssuedCertificate, issuedCertificateData secrets.IntermediateCAData) (*corev1.Secret, error) {
@mihmatache Can you elaborate on why the existing certs generated for shared trust can't be used for the limited trust scenario?

The issued certificates that are generated for shared trust should be re-usable for limited trust (i.e. as the credentials for the egress gateways) because they are derived from a common root.

2021-02-05 15:32 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +}
We should reuse the existing federation logic instead of duplicating the entire federation pipeline for limited vs. shared trust. Here's my rationale:

The trust model is but one aspect of federation. Most of the other federation logic remains the same (i.e. setting up remote ServiceEntries/DestinationRules/VirtualServices, creating the EnvoyFilter for the tcp rewrite, updating the status of the VirtualMesh).

Based on the [istio guide here](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/#perform-mutual-tls-origination-with-an-egress-gateway), the only modifications that limited trust requires is:

1. creating a modified egress Gateway (where we set the TLS cert to those generated from the certificate signing process)
2. creating a modified VirtualService for each remote service in order to route requests through the egress gateway
3. (assuming istio 1.8) configuring remote DestinationRules with `credentialName` that points at the issued certs

2021-06-01 20:37 UTC, harveyxia commented
closing due to inactivity—we've left a number of comments and questions that need to be addressed before this PR can proceed, the primary concerns are [summarized here](https://github.com/solo-io/gloo-mesh/pull/1084#discussion_r571052546)

2021-06-01 20:37 UTC, closed without merging