Docs wasmctl guide
solo-io/gloo-mesh pull request #1159
Opened 2020-12-16 14:51 UTC by ned1313

Adding a guide for the `meshctl wasm` plugin.

2020-12-16 15:00 UTC, ned1313 commented on docs/content/guides/wasm_meshctl.md
> +curl solo.io/meshctl-wasm/foo/bar/install | sh
This command needs to be updated before the PR is merged.

2020-12-18 16:27 UTC, ryantking requested changes
Looks good, few minor changes

2020-12-18 16:27 UTC, ryantking commented on docs/content/guides/wasm_meshctl.md
> +curl solo.io/meshctl-wasm/foo/bar/install | sh
Here's the final command:
```
curl -sL https://storage.googleapis.com/gloo-mesh-enterprise/meshctl-plugins/wasm/install.sh | sh
```

2020-12-18 16:27 UTC, ryantking commented on docs/content/guides/wasm_meshctl.md
> +To illustrate these concepts, we will assume that you have already followed the [Wasm Extension Guide for Gloo Mesh Enterprise]({{% versioned_link_path fromRoot="/guides/wasm_extension/" %}}) to get
Where is this guide?

2020-12-18 16:27 UTC, ryantking commented on changelog/v0.11.2/docs-meshctl-wasm.yaml
> +    description: Add a guide for using meshctl wasm plugin
Newline

2020-12-18 16:27 UTC, ryantking commented on docs/content/guides/wasm_meshctl.md
> +  --remote-kubecontext $MGMT_CONTEXT
This should probably be something different since the mgmt context and remote context are two different clusters. With the `demo istio-multicluster` setup, it would be `kind-mgmt-cluster` and `kind-remote-cluster` respectively.

2020-12-18 16:35 UTC, joekelley commented on docs/content/guides/wasm_meshctl.md
> +  --remote-kubecontext $MGMT_CONTEXT
I think this is still valid, it just means that the guide won't demonstrate that this works in a multicluster scenario

2020-12-18 16:46 UTC, joekelley commented on docs/content/guides/wasm_meshctl.md
> +  --filter-name meshctl-filter \
```suggestion
  --deployment-name meshctl-filter \
```

2020-12-18 16:49 UTC, joekelley commented on docs/content/guides/wasm_meshctl.md
> +To illustrate these concepts, we will assume that you have already followed the [Wasm Extension Guide for Gloo Mesh Enterprise]({{% versioned_link_path fromRoot="/guides/wasm_extension/" %}}) to get
Instead of recommending this entire guide, we should point users to just this section https://docs.solo.io/gloo-mesh/latest/guides/wasm_extension/#ensure-the-wasm-agent-is-installed

2020-12-18 21:24 UTC, joekelley approved these changes

2020-12-18 21:50 UTC, ryantking approved these changes

2020-12-18 21:50 UTC, merged