Clarify which relay address to use for a LoadBalancer type ingress
solo-io/gloo-mesh pull request #1380
Opened 2021-04-01 16:55 UTC by ashleywang1

2021-04-01 16:56 UTC, ashleywang1 commented
/skip-changelog

2021-04-01 17:18 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +Assuming your ingress service is running on a node port, you can get the address of this ingress for use during [cluster registration]({{% versioned_link_path fromRoot="/setup/cluster_registration/en
These instructions are for getting the relay server address for a LoadBalancer istio ingress, rather than a LoadBalancer enterprise-networking service

2021-04-01 17:19 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +Assuming your ingress service is running on a node port, you can get the address of this ingress for use during [cluster registration]({{% versioned_link_path fromRoot="/setup/cluster_registration/en
perhaps we should move this block below to the Istio Ingress section?

2021-04-01 17:22 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +{{% notice note %}}This type of ingress is recommended if you are using GKE or Amazon EKS.{{% /notice %}}
I don't think this notice belongs here at the top level of this section. I'm also hesitant to provide this prescription, since there's a lot to consider when a user determines their ingress approach.

2021-04-01 17:35 UTC, ashleywang1 commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +Assuming your ingress service is running on a node port, you can get the address of this ingress for use during [cluster registration]({{% versioned_link_path fromRoot="/setup/cluster_registration/en
Modified the beginning part a bit to make it more clear.

2021-04-01 19:46 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +Assuming your ingress service is running on a node port, you can get the address of this ingress for use
Let's update this to use our tabbed content view; we can have a tab for NodePort ingress services and another for LoadBalancer ingress services.

2021-04-01 19:49 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +Another option is to set your ingress service as a LoadBalancer type.
I don't think we need to include this here, users can determine their ingress service type when they install istio.

2021-04-01 20:59 UTC, ashleywang1 commented
/skip-changelog

2021-04-02 12:44 UTC, EItanya commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
>  MGMT_INGRESS_ADDRESS=$(kubectl get node -ojson | jq -r ".items[0].status.addresses[0].address")
This will only work if there is 1 node, we need to change this command to get the node on which the `istio-ingressgateway` is running

2021-04-02 12:45 UTC, EItanya requested changes
This will only work if there is 1 node, we need to change this command to get the node on which the `istio-ingressgateway` is running

2021-04-02 14:39 UTC, harveyxia commented on docs/content/concepts/role_based_api.md
> +**TrafficPolicyScope:** [TrafficPolicies]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1alpha2.traffic_policy/" %}}) operate on routes between workloa
```suggestion
**TrafficPolicyScope:** [TrafficPolicies]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1.traffic_policy/" %}}) operate on routes between workloads and Destinations.
```

2021-04-02 14:39 UTC, harveyxia commented on docs/content/concepts/role_based_api.md
> +**AccessPolicyScope:** [AccessPolicies]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1alpha2.access_policy/" %}}) operate on routes between identities
```suggestion
**AccessPolicyScope:** [AccessPolicies]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1.access_policy/" %}}) operate on routes between identities (which represent a set of workloads) and Destinations.
```

2021-04-02 14:40 UTC, harveyxia commented on docs/content/concepts/concepts.md
> +A [`TrafficPolicy`]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1alpha2.traffic_policy/" %}}) applies between a set of sources (workloads) and destin
```suggestion
A [`TrafficPolicy`]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1.traffic_policy/" %}}) applies between a set of sources (workloads) and destinations, and is used to describe rules like "when A sends POST requests to B, add a header and set the timeout to 10 seconds". Or "for every request to services on cluster C, increase the timeout and add retries". As of this release, traffic policies support timeouts, retries, CORS, traffic shifting, header manipulation, fault injection, subset routing, weighted destinations, and more. Note that some meshes don’t support all of these features; Gloo Mesh will translate as best it can into the underlying mesh configuration, or report an error back to the user.
```

2021-04-02 14:40 UTC, harveyxia commented on docs/content/concepts/concepts.md
> +An [`AccessPolicy`]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1alpha2.access_policy/" %}}) also applies between sources (this time representing ide
```suggestion
An [`AccessPolicy`]({{% versioned_link_path fromRoot="/reference/api/github.com.solo-io.gloo-mesh.api.networking.v1.access_policy/" %}}) also applies between sources (this time representing identities) and destinations, and is used to finely control which services are allowed to communicate. On the virtual mesh, a user can specify a global policy to restrict access, and require users to specify access policies in order to enable communication to services.
```

2021-04-07 13:25 UTC, ashleywang1 commented
/skip-changelog

2021-04-07 16:19 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +LoadBalancer type is usually better, but sometimes your environment doesn't allow it.
nit: let's avoid being prescriptive here. A lot of our docs are centered around the kind-mgmt-cluster/kind-remote-cluster example, and it uses nodeport. I think we can remove this sentence.

2021-04-07 16:19 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +{{< tab name="NodePort" codelang="yaml">}}
```suggestion
{{< tab name="NodePort" codelang="shell">}}
```

2021-04-07 16:19 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +{{< tab name="LoadBalancer" codelang="yaml">}}
```suggestion
{{< tab name="LoadBalancer" codelang="shell">}}
```

2021-04-07 16:20 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +In either case, you can get the address of this ingress for use
also, the steps below assume that users named their ingress port "https". we should state that assumption

2021-04-07 16:21 UTC, joekelley commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +that means you have multiple nodes, and the istio-ingressgateway isn't
```suggestion
that could mean you have multiple nodes, and the istio-ingressgateway isn't
```

2021-04-07 17:44 UTC, EItanya approved these changes

2021-04-08 18:02 UTC, ashleywang1 commented
/skip-changelog

2021-04-09 17:20 UTC, ashleywang1 commented
/skip-changelog

2021-04-09 17:24 UTC, harveyxia commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +If you are using a NodePort and are failing to connect to relay,
Can we also highlight this assumption with a comment in the NodePort tab between L98 and L99?

2021-04-09 17:37 UTC, harveyxia submitted a review, later dismissed

2021-04-09 19:49 UTC, ashleywang1 commented
/skip-changelog

2021-04-09 20:21 UTC, jenshu commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +Some useful scripts for finding the ingress address can be found below (we assume that the ingress port is named https.):
```suggestion
Some useful scripts for finding the ingress address can be found below (we assume that the ingress port is named https):
```

2021-04-09 20:22 UTC, jenshu commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +// the pod `spec.nodeName` field)
for shell commands should we use `#` for comments?

2021-04-09 20:24 UTC, jenshu commented on docs/content/setup/prerequisites/enterprise_prerequisites.md
> +# on which the istio-ingressgateway pod is deployed on (indicated by
```suggestion
# on which the istio-ingressgateway pod is deployed (indicated by
```

2021-04-09 20:25 UTC, jenshu approved these changes

2021-04-09 20:25 UTC, jenshu commented
/skip-changelog

2021-04-09 20:41 UTC, merged