Additional translate traffic policy utils
solo-io/gloo-mesh pull request #1526
Opened 2021-05-10 13:45 UTC by npolshakova

See solo-io/gloo-mesh-enterprise#419 and https://github.com/solo-io/gloo-mesh-enterprise/pull/480

2021-05-10 13:56 UTC, ilackarms commented on pkg/mesh-networking/translation/utils/trafficpolicyutils/translate_header_manipulation.go
>  package trafficpolicyutils
we probably want to rename the file since it's no longer gonna be responsible solely for header manipulation

2021-05-12 14:03 UTC, Sodman commented on pkg/mesh-discovery/translation/mesh/detector/istio/istio_mesh_detector_test.go
>  							WorkloadLabels: workloadLabels,
Name is now part of the discovered mesh's IngressGatewayInfo
```suggestion
							Namespace:      "namespace",
							Name:           "ingress-svc",
							WorkloadLabels: workloadLabels,
```

2021-05-12 15:25 UTC, harveyxia commented
Can we reuse this logic in the existing TrafficPolicy decorators?

2021-05-12 15:34 UTC, ilackarms requested changes
looks like we still need to update the traffic policy decorators to use these util functions (rather than have duplicated logic)

2021-05-13 13:15 UTC, harveyxia commented
Also let's add unit tests

2021-05-13 18:43 UTC, Sodman commented
> Also let's add unit tests

I think the existing unit tests for the traffic policy functionality should cover this already, as it's not actually changing behavior, just moving the logic into a shared package. We'll want a few smoke tests on the Enterprise side to make sure that this shared logic is actually running in the translation loop though.

2021-05-13 20:39 UTC, merged