Backup docker images to Quay
solo-io/gloo-mesh pull request #1576
Opened 2021-05-24 15:40 UTC by ashleywang1

2021-05-25 15:48 UTC, ashleywang1 commented
Tested in this run: https://github.com/solo-io/gloo-mesh/pull/1583/checks?check_run_id=2666909270
Failure does not cause the entire workflow to fail

Currently updating the QUAY password.

2021-05-26 11:14 UTC, EItanya requested changes
Why did we switch from quay to docker hub?

2021-05-26 13:34 UTC, joekelley commented
We switched because:
- we have had less luck with stability in quay in the past.
- we already have repos for the GM images in dockerhub.
- we already have the secrets in place for dockerhub in this repo.

2021-05-26 20:33 UTC, EItanya approved these changes

2021-05-26 20:33 UTC, merged