Multiple ingress gateways
solo-io/gloo-mesh pull request #1691
Opened 2021-06-28 14:11 UTC by ashleywang1

2021-06-28 14:13 UTC, ashleywang1 commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +				gatewayTlsPortName := "tls"
I'm not sure if this code can be DRY-ed, but if so, I'll use the federation default instead of making a new constant

2021-06-28 14:15 UTC, ashleywang1 commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +	var selectedIngressGatewayList []*ingressGatewayInfo
We create a list of (destination, tls port) tuples and each results in a gateway.

2021-06-28 14:20 UTC, ashleywang1 commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +				Name:        gwName,
Ideas on how to name this gateway if there are multiple? Maybe add the gatewayTlsPortName at the end, e.g. virtual-mesh-gloo-mesh-tls gateway?

2021-06-28 14:37 UTC, harveyxia commented on api/common/v1/selectors.proto
> +message IngressGatewayServiceSelector {
```suggestion
message IngressGatewaySelector {
```

2021-06-28 14:38 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    // If omitted, the default ingressgateway destination will be used.
```suggestion
    // If omitted, a mesh-specific default ingress gateway destination will be used.
```

2021-06-28 14:53 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    // in order to be recognized as an ingress gateway. If not specified, will default to `tls`.
```suggestion
    // Specify by name the TLS port on the ingress gateway destination. If not specified, will default to "tls".
```

2021-06-28 14:53 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    // If omitted, the selected Destinations will be federated to all Meshes in the VirtualMesh.
```suggestion
    // The Meshes for which the selected Destinations will be configured as ingress gateways. All referenced Meshes must exist in this VirtualMesh.
    // If omitted, the selected Destinations will be configured as ingress gateways for all Meshes in the VirtualMesh.
```

2021-06-28 14:53 UTC, harveyxia commented on api/discovery/v1/mesh.proto
> +    repeated IngressGatewayDestination ingress_destinations = 4;
```suggestion
    // The Destination(s) acting as ingress gateways for east west traffic.
    repeated IngressGateway east_west_ingress_gateways = 4;
```

2021-06-28 14:53 UTC, harveyxia commented on api/discovery/v1/mesh.proto
> +    }
```suggestion
    message IngressGateway {
        // The Destination on the mesh that acts as an ingress gateway for the mesh.
        .core.skv2.solo.io.ObjectRef destination_ref = 1;

        // The name of the TLS port on the ingress gateway Destination.
        string tls_port_name = 2;
    }
```

2021-06-28 14:53 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +	// [Defaults to](https://github.com/istio/istio/blob/ab6cc48134a698d7ad218a83390fe27e8098919f/pkg/config/constants/constants.go#L73) `{"istio": "ingressgateway"}`.
no need to use markdown in Go comments since they don't get rendered

2021-06-28 14:57 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +						fmt.Sprintf("One or more of your ingress gateway destination selectors did not match any destinations"),
```suggestion
						fmt.Sprintf("No Destinations selected as ingress gateway. At least one must be selected."),
```

2021-06-28 14:58 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +					if selectorutils.SelectorMatchesDestination(ingressGatewayServiceSelector.GetDestinationSelectors(), destination) {
We also need to validate that Destinations selected by direct reference exist

2021-06-28 14:59 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +		if len(vMesh.Spec.GetFederation().GetIngressGatewayServiceSelectors()) > 0 {
Can we place the ingress gateway selection logic into its own function? It's confusing to colocate it in a function doing something unrelated (validating the one VM per Mesh constraint)

2021-06-28 15:25 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +	for _, ingressGatewayServiceSelector := range virtualMesh.GetSpec().GetFederation().GetIngressGatewayServiceSelectors() {
discussed offline—we'll want to use the applier convention here, add a [line here](https://github.com/solo-io/gloo-mesh/blob/558c3c8dbe22fa02ad28a9add14b18abd4f6d403/pkg/mesh-networking/apply/applier.go#L127):

```golang
for _, mesh := range input.Meshes().List() {
	mesh.Status.AppliedVirtualMesh = getAppliedVirtualMesh(input.VirtualMeshes().List(), mesh)
	mesh.Status.EastWestIngressGateways = getEastWestIngressGateways(input.VirtualMeshes().List(), mesh, input.Destinations().List())
}
```

that resolves the selected Destinations for ingress gateways on the mesh. Then here, the translator reads directly from the Mesh status for the ingress gateway destinations

2021-06-28 15:26 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +				Name:        gwName,
Since the Gateway CRD will map 1-1 with respect to a (VirtualMesh, Destination) tuple, we can modify the `BuildGatewayName` function to construct a unique name from the VirtualMesh and Destination object meta

2021-06-28 16:45 UTC, ashleywang1 commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +					if selectorutils.SelectorMatchesDestination(ingressGatewayServiceSelector.GetDestinationSelectors(), destination) {
That should be checked in the `SelectorMatchesDestination` function

2021-06-28 17:08 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +					if selectorutils.SelectorMatchesDestination(ingressGatewayServiceSelector.GetDestinationSelectors(), destination) {
to clarify, we should report an error if any direct references don't exist, [we can reuse this function](https://github.com/solo-io/gloo-mesh/blob/8d4fbb67b918dbee810d449b3ee797ca40393d8e/pkg/mesh-networking/apply/configtarget/config_target_validator.go#L102)

2021-06-28 18:24 UTC, ashleywang1 commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +				Name:        gwName,
This is resulting in names like
```
istio-system   virtual-mesh-gloo-mesh-istio-in-01fe4f88d1b6407050af9b7967b4957   2m49s
istio-system   virtual-mesh-gloo-mesh-istio-in-ea0fbf7b9febcbec1fd78df0b653eb9   2m48s
```

2021-06-28 19:20 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +				if meshRef.GetName() == mesh.GetName() && meshRef.GetNamespace() == mesh.GetNamespace() {
we can use skv2's `ezkube.RefsMatch` for this

2021-06-28 19:39 UTC, harveyxia requested changes
There's some more work to do for the Destination federation translation, [see this TODO](https://github.com/solo-io/gloo-mesh/blob/main/pkg/mesh-networking/translation/istio/destination/federation/federation_translator.go#L183-L185)

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +				if destination.Spec.GetExternalService() != nil {
```suggestion
				if destination.Spec.GetKubeService() == nil {
```

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +					continue
we'll want to throw an error here if the user selects a non-k8s destination, and propagate that to the status

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +				gatewayTlsPortName := "tls"
use the constant defined [here](https://github.com/solo-io/gloo-mesh/blob/dcdbfbbb98a8babf29fc2c55d02e4cdf5760d785/pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go#L27). also include a comment describing that it's the default, hardcoded fallback value

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +						if len(destination.Spec.GetKubeService().GetWorkloadSelectorLabels()) != 0 {
code style nit:

you can express required conditions by continuing if they don't hold to avoid nested levels of indentation:

```golang
if !selectorutils.SelectorMatchesDestination(ingressGatewayServiceSelector.GetDestinationSelectors(), destination) {
    continue
}
// logic here
```

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +			// Check the mesh specific default exists
We should have the following fallback behavior, in order of precedence:

1. Use the deprecated ingress gateway info on the Mesh object
2. If #1 doesn't exist, use default fallback values

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +					if destination.Spec.GetKubeService().GetWorkloadSelectorLabels()["istio"] == "ingressgateway" {
use the [constant defined here](https://github.com/solo-io/gloo-mesh/blob/2fa37161ba5ef92097b3f28a49a32f3ece78849e/pkg/common/defaults/istio.go#L6)

2021-06-28 19:39 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +			if !defaultExists {
we can consolidate this logic into the `matchedDestinations` count above, my reasoning being that we don't need a separate error message for not finding the default ingress, we can just use the same error above (`"No Destinations selected as ingress gateway. At least one must be selected."`)

2021-06-28 19:41 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    // If omitted, a mesh-specific default ingress gateway destination will be used.
```suggestion
    // If omitted, a mesh-specific default ingress gateway destination will be used.
    // For Istio, any Kubernetes Service(s) with the label pair `{"istio": "ingressgateway"}` will be selected.
```

2021-06-28 20:48 UTC, ashleywang1 commented on pkg/mesh-networking/apply/applier.go
> +					continue
We can just check it in the config target validator and put it in the status directly there.

2021-06-29 13:47 UTC, harveyxia commented
Can we add a unit test for the new applier logic that applies east west gateways to the Mesh status?

2021-06-29 14:05 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +				Name:        gwName,
discussed offline, we'll use destination name + destination namespace (no need to include VM name/namespace)

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +		vMesh := vMesh
I don't think this is needed

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +		eachMeshIsAllSet := make(map[string]bool)
We can make this code more readable by using a string set (import from `"k8s.io/apimachinery/pkg/util/sets"`, and use `sets.NewString`)) named `meshesWithSelectedIngressDestination` keyed on the resource key of the mesh, where existence means the mesh has a selected ingress gateway

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +				// Currently, we can only create gateways out of kube service destination types.
we need to ignore destinations don't belong to the mesh

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +			if destination.Spec.GetKubeService().GetWorkloadSelectorLabels()["istio"] == "ingressgateway" {
Can we hoist the label key and value into constants? We can define them in `federation_translator.go`:

```
// Defaults to {"istio": "ingressgateway"} based on https://github.com/istio/istio/blob/ab6cc48134a698d7ad218a83390fe27e8098919f/pkg/config/constants/constants.go#L73
IstioGatewayLabelKey = "istio"
IstioIngressGatewayLabelValue = "ingressgateway"
DefaultGatewayWorkloadLabels = map[string]string{IstioGatewayLabelKey: IstioIngressGatewayLabelValue}
```

and reuse them here

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +						fmt.Sprintf("Attempting to select ingress gateway destination: %v", err))
this error message needs to be corrected

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +						vMesh.Status.Errors = append(
I don't think we need to signal this to the user—it's a discovery field so the deprecation is internal to our system

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +		if c.meshes != nil {
we don't need this conditional, it's handled by `c.meshes.List()`

2021-06-30 15:41 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +				if _, ok := eachMeshIsAllSet[sets.Key(mesh)]; ok {
this should be `!ok`

2021-06-30 15:44 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +	defaultGatewayWorkloadLabels = map[string]string{"istio": "ingressgateway"}
this already exists [here](https://github.com/solo-io/gloo-mesh/blob/2fa37161ba5ef92097b3f28a49a32f3ece78849e/pkg/common/defaults/istio.go#L6)

2021-06-30 15:49 UTC, harveyxia commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +		// fall back to old behavior
we should encapsulate the fallback behavior in the applier—the applier should select ingress gateway services based on the fallback behavior and apply them to the mesh status. Then this translator can just fetch the ingress gateway data from the mesh status without knowing anything about fallback behavior

2021-06-30 16:02 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +	if len(selectedIngressGatewayList) == 0 {
discussed offline for fallback behavior:

// 1. look at mesh ingress gateway info (if it's populated) for the ingress Destination
// 2. look for a Destination in the mesh with the default hardcoded workload label pair + tls port name

2021-06-30 16:06 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +	c.validateMeshIngressGatewaysForEachVirtualMesh(virtualMeshes)
discussed offline, we can move all of this logic into the applier

2021-07-01 15:16 UTC, ashleywang1 commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +						fmt.Sprintf("Attempting to select ingress gateway destination: %v", err))
It'll look like this: ```Attempting to select ingress gateway destination: destination x has no port named x"

2021-07-01 15:17 UTC, ashleywang1 commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +		if c.meshes != nil {
Some tests ended up hitting this case because they set c.meshes to nil

2021-07-01 15:19 UTC, harveyxia commented on pkg/mesh-networking/apply/configtarget/config_target_validator.go
> +		if c.meshes != nil {
if `c.meshes` is nil, `c.meshes.List()` will return nil, [see here](https://github.com/solo-io/gloo-mesh/blob/073a2202604aaf1a981f4ca94cfb53810e916bb2/pkg/api/discovery.mesh.gloo.solo.io/v1/sets/sets.go#L501-L503)

2021-07-06 12:44 UTC, EItanya requested changes
Need to have further discussion about move to circle ci

2021-07-06 14:36 UTC, harveyxia commented
> Need to have further discussion about move to circle ci

Discussed offline, we'll only deploy the second ingress gateway in closed source. The open source e2e test will only test the ability to explicitly select the default istio ingress gateway (and not the ability to select and load balance across 2 ingress gateways).

2021-07-06 14:59 UTC, EItanya commented on ci/setup-funcs.sh
> +  port1=$2
Are we exposing these args through the e2e golang code?

2021-07-06 15:02 UTC, harveyxia commented on ci/setup-funcs.sh
> +  port1=$2
they can be set through environment variables, see the changes in `ci/setup-kind.sh`

2021-07-06 15:08 UTC, EItanya commented on ci/setup-funcs.sh
> +  ingressPort2=$3
I don't think we need this second port as an arg to the istio functions anymore since we are only creating a single Gateway

2021-07-06 15:10 UTC, harveyxia commented on ci/setup-funcs.sh
> +  ingressPort2=$3
yeah i cleaned up the scripts, see commit `1e39e30`

2021-07-07 12:57 UTC, EItanya commented on ci/setup-funcs.sh
> +  ingressPort1=$2
Can we rename these to `ingressPort` since there is only 1 of them

2021-07-07 13:02 UTC, EItanya commented on pkg/common/defaults/istio.go
>  // https://github.com/istio/istio/blob/4e27ddc64f6a12e622c4cd5c836f5d7edf94e971/istioctl/cmd/describe.go#L1138
No longer relevant

2021-07-07 13:04 UTC, EItanya commented on test/e2e/istio/pkg/tests/federation.go
> +									"istio": "ingressgateway",
`traffic: east-west`?

2021-07-07 13:05 UTC, EItanya commented on pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go
> +
Nit: unecessary newline

2021-07-07 13:05 UTC, harveyxia commented on test/e2e/istio/pkg/tests/federation.go
> +									"istio": "ingressgateway",
the other ingress gateway has label `istio: ingressgateway2` so this label pair alone should be sufficient to distinctly select the first ingress gateway

2021-07-07 13:11 UTC, EItanya commented on pkg/mesh-networking/apply/applier.go
> +		if appliedIngressGateway, err := buildAppliedIngressGateway(destination, defaults.IstioGatewayTlsPortName); err != nil {
Are we planning on allowing users to change this port name? This [issue](https://github.com/solo-io/gloo-mesh/issues/1705) is not quite the same, but just wondering if that's something we care about

2021-07-07 13:14 UTC, EItanya commented on pkg/mesh-networking/apply/applier.go
> +	// Resolve all of the VM’s ingress gateway selectors to a list of (Destination, tls port) tuples that belong to the mesh
Super Nit, I was very confused why we were talking about Virtual Machines 😆 
```suggestion
	// Resolve all of the VirtualMesh’s ingress gateway selectors to a list of (Destination, tls port) tuples that belong to the mesh
```

2021-07-07 13:15 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +		if appliedIngressGateway, err := buildAppliedIngressGateway(destination, defaults.IstioGatewayTlsPortName); err != nil {
This is the default gateway tls port name that we fall back on in the case that 1) we didn't find any ingress destinations from the user provided ingress selector and 2) we didn't find any ingress gateways in the deprecated Mesh ingress gateways field

Because we allow users to [configure the tls port name ](https://github.com/solo-io/gloo-mesh/pull/1691/files#diff-01a5bfa7395892a4c2a33dfcf287029adc8ab84eb3df83d2bceec1feaec06983R131) through the ingress gateway selector, I feel comfortable making the fallback default non-configurable. What do you think?

2021-07-07 13:16 UTC, EItanya commented on pkg/mesh-networking/apply/applier.go
> +		if appliedIngressGateway, err := buildAppliedIngressGateway(destination, defaults.IstioGatewayTlsPortName); err != nil {
Nvm, I see that this is the default function, sorry

2021-07-07 13:18 UTC, EItanya commented on api/common/v1/selectors.proto
> +    repeated .core.skv2.solo.io.ObjectRef meshes = 3;
Is there any way we can make this a label set rather than a list. A list can become invalid very quickly, and is potentially very verbose. I suppose we have the same issue for the VirtualMesh Mesh selection now as well.

2021-07-07 13:18 UTC, EItanya commented on api/common/v1/selectors.proto
> +    string gateway_tls_port_name = 2;
Can we also specify by number in a `oneof`?

2021-07-07 13:20 UTC, EItanya commented on api/discovery/v1/mesh.proto
> +        // The externally accessible IP addresses.
Only IPs or can these also be hostnames, and does that make a difference?

2021-07-07 13:20 UTC, EItanya commented on api/discovery/v1/mesh.proto
> +        uint32 tls_container_port = 4;
Wdyt about removing `tls` from these since the user can use a different name other than `tls` for the port name, and this feels like a bit of a relic. Or is this more to do with the type of traffic? Still feels a bit prescriptive.

2021-07-07 13:23 UTC, EItanya commented on pkg/mesh-networking/apply/applier.go
> +			if len(kubeService.GetWorkloadSelectorLabels()) == 0 {
Just wondering why this is automatically an error? What does Kubernetes do if there is a service with no workload selector labels?

2021-07-07 13:23 UTC, EItanya commented on pkg/mesh-networking/apply/applier.go
> +					fmt.Sprintf("attempting to select ingress gateway destination %v with no workload labels", sets.Key(destination)),
```suggestion
					fmt.Sprintf("attempting to select ingress gateway destination %v with no workload selector labels", sets.Key(destination)),
```

2021-07-07 13:47 UTC, harveyxia commented on pkg/mesh-networking/apply/applier.go
> +			if len(kubeService.GetWorkloadSelectorLabels()) == 0 {
It's possible for k8s services to have no selectors, see [here](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors). So this is a guard rail in case the user accidentally selects an externally addressable service that has no selector

2021-07-07 13:49 UTC, harveyxia commented on api/discovery/v1/mesh.proto
> +        uint32 tls_container_port = 4;
Interesting point—we currently prescribe TLS-secured traffic for cross cluster communication because we set tls `AUTO_PASSTHROUGH` on our Gateway. If we want to relax that constraint we'll have to make some changes to the way we configure the Gateway, and possibly some API changes as well.

2021-07-07 13:51 UTC, harveyxia commented on api/discovery/v1/mesh.proto
> +        // The externally accessible IP addresses.
good call, these can be either IPs or hostnames. It affects the federated ServiceEntry resolution mode which handles the different scenarios (e.g. only IPs, only hostnames, mix of ips + hostnames, etc)

I'll clarify the docstring

2021-07-07 13:55 UTC, EItanya commented on pkg/mesh-networking/apply/applier.go
> +			if len(kubeService.GetWorkloadSelectorLabels()) == 0 {
Gotcha, I think this is a ok guard rail for now, but this could be a legitimate use case I suppose

2021-07-07 13:56 UTC, EItanya commented on api/discovery/v1/mesh.proto
> +        uint32 tls_container_port = 4;
Just to clarify, the traffic does need to be TLS. But the name I think had to do with the port name, not the traffic type. Might be overthinking it though

2021-07-07 13:57 UTC, EItanya commented on test/e2e/istio/pkg/tests/federation.go
> +									"istio": "ingressgateway",
I just recommended this because it's not the default, so it will ensure we're not falling back to the default for some unknown reason.

2021-07-07 14:00 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    repeated .core.skv2.solo.io.ObjectRef meshes = 3;
very good question—I couldn't come up with a better way to represent these semantics in a structured way.

We could couple any per-mesh config with the [`meshes` field](https://github.com/solo-io/gloo-mesh/blob/f43f69c716c5be105dc229030e592dd2f0e6bc2e/api/networking/v1/virtual_mesh.proto#L21), but that also complicates the UX. Let's discuss offline

2021-07-07 15:28 UTC, harveyxia commented on api/discovery/v1/mesh.proto
> +        uint32 tls_container_port = 4;
discussed offline—we'll remove the `tls` suffix since the port can be any port and k8s itself has no notion of tls secured ports

2021-07-07 19:20 UTC, EItanya commented on api/common/v1/selectors.proto
> +    repeated .core.skv2.solo.io.ObjectRef meshes = 3;
On a separate note: How does this field interact with the federation selectors? Do we need both layers?

2021-07-08 12:48 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    repeated .core.skv2.solo.io.ObjectRef meshes = 3;
They are separate—federation selectors affect what destinations get federated, and ingress gateway selectors affect which externally accessible k8s services are used for remote traffic (i.e. the address used to populate SE's for federated destinations on remote clusters)

2021-07-08 12:48 UTC, harveyxia commented on api/common/v1/selectors.proto
> +    repeated .core.skv2.solo.io.ObjectRef meshes = 3;
They are separate—federation selectors affect what destinations get federated, and ingress gateway selectors affect which externally accessible k8s services are used for remote traffic (i.e. the address used to populate SE's for federated destinations on remote clusters)

2021-07-08 14:35 UTC, EItanya commented on api/common/v1/selectors.proto
> +    repeated .core.skv2.solo.io.ObjectRef meshes = 3;
Discussed offline. The core of my argument here is that this field is potentially more complicated than the value it offers. Because of how API deprecation works we can never remove fields only add, so my recommendation would be to leave this field out for the first version, and add it in later if users need it.

The main source of the complication being the list of meshes. Mesh reference lists are cumbersome for the user, and we should revisit this when we have label selection for meshes.

2021-07-09 15:59 UTC, EItanya approved these changes

2021-07-09 16:29 UTC, harveyxia approved these changes

2021-07-09 16:30 UTC, merged