Gateway docs
solo-io/gloo-mesh pull request #1745
Opened 2021-07-26 12:42 UTC by Sodman

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +Gloo Mesh Gateway is an abstraction built on top of Istio ingress gateway, and Envoy proxy. It can be used as a way to simplfy the configuration of ingress traffic rules, while retaining seamless int
```suggestion
Gloo Mesh Gateway is an abstraction built on top of [Istio's ingress gateway model](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) and the underlying Envoy proxies. It can be used as a way to simplify the configuration of ingress traffic rules while retaining seamless integration with your service mesh. It also adds powerful mutli-cluster, multi-mesh capabilities for scalability.
```

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +### Example 2: Mutli cluster, Single Gateway
```suggestion
### Example 2: Multicluster, Single Gateway
```

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +### Example 3: Mutli cluster, Multi Gateway
```suggestion
### Example 3: Multicluster, Multi Gateway
```

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +A VirtualGateway resource will define the listeners, which protocols and ports to listen on. It will also define which filters are attached, by allowing users to specify a FilterChain (or multiple Fi
```suggestion
A VirtualGateway resource will define the [Envoy listeners](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listeners), i.e. the protocols and ports to listen on. It will also define which Envoy filters are attached, by allowing users to specify a [FilterChain](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/network_filter_chain) (or multiple FilterChains). It attaches to existing ingress gateway workloads via a workload selector, and specifies one or more VirtualHost configurations to configure routing rules. A single VirtualGateway can apply to multiple ingress deployments across meshes and clusters contained within a VirtualMesh. Attached Gateways will be listed in the status of the VirtualGateway. In order to perform cross-mesh routing, the Gateway Mesh and Destination Mesh _must be contained in a single VirtualMesh with federation enabled_.
```

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +Virtual Hosts are selected by a Virtual Gateway. A single VirtualHost can be selected by multiple VirtualGateways. VirtualHosts are responsible for configuring top level settings, such as domains. In
Can we do a find+replace for all occurrences of "Virtual Host" and "Virtual Hosts" and replace with "VirtualHost" and "VirtualHosts"? Same for "Virtual Gateway(s)" and "Route Table(s)"

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +A Route Table is effectively a list of Routes. It exists only to be delegated to from VirtualHosts, or other RouteTables. This allows users to separate configuration and ownership across the organiza
```suggestion
A Route Table is effectively a list of Routes. It exists only to be delegated to from VirtualHosts, or other RouteTables. This allows users to separate configuration and ownership across the organization. For example an app-level team may want to configure all of the low-level endpoints that are sent to their service, but may not have control over which domains they can serve traffic on, or what the authorization policies are. Routes configured in RouteTables will by default inherit any options configured by their parent delegating resource (RouteTable or VirtualHost), for example, timeout or retry settings.
```

2021-07-27 15:58 UTC, harveyxia commented on docs/content/guides/gateway/concepts.md
> +- A kubernetes service, the most commonly used option. Notably, this is a service in a specific _cluster_.
Make sure to capitalize all occurrences of "kubernetes"

```suggestion
- A Kubernetes service, the most commonly used option. Notably, this is a service in a specific _cluster_.
```

2021-07-28 14:39 UTC, ashleywang1 commented on docs/content/guides/gateway/ratelimiting/_index.md
> +apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
This is incorrectly formatted (spacing)

2021-07-28 14:45 UTC, ashleywang1 commented on docs/content/guides/gateway/ratelimiting/crds/_index.md
> +kubectl apply -f - << EOF
spacing issues here as well

2021-07-29 11:30 UTC, EItanya commented on docs/content/guides/gateway/_index.md
> +Gloo Mesh Gateway allows users to harness the power of Envoy proxy as an Ingress Gateway for their service mesh, while keeping the simplicy of the Gloo Mesh API. This allows for simplifying your setu
`This allows for simplifying your setup by writing advanced configuration once, and re-using it in multiple places and different contexts.` Is a run on, consider removing the final bit

2021-07-29 11:30 UTC, EItanya commented on docs/content/guides/gateway/_index.md
> +Gloo Mesh Gateway allows users to harness the power of Envoy proxy as an Ingress Gateway for their service mesh, while keeping the simplicy of the Gloo Mesh API. This allows for simplifying your setu
```suggestion
Gloo Mesh Gateway allows users to harness the power of Envoy proxy as an Ingress Gateway for their service mesh, while keeping the simplicy of the Gloo Mesh API. This allows for simplifying your setup by writing advanced configuration once, and re-using it in multiple places and different contexts. For example, a rate limit policy could be written once, and applied to both traffic coming into the cluster via an ingress gateway as well as traffic inside the cluster travelling east to west.
```

2021-07-29 11:32 UTC, EItanya commented on docs/content/guides/gateway/concepts.md
> +Gloo Mesh Gateway is an abstraction built on top of [Istio's ingress gateway model](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) and the underlying Envoy proxies. I
```suggestion
Gloo Mesh Gateway is an abstraction built on top of [Istio's ingress gateway model](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/). It can be used as a way to simplify the configuration of ingress traffic rules while retaining seamless integration with your service mesh. It also adds powerful mutli-cluster, multi-mesh capabilities to your gateway.
```

2021-07-29 11:33 UTC, EItanya commented on docs/content/guides/gateway/concepts.md
> +Gloo Mesh Gateway is an abstraction built on top of [Istio's ingress gateway model](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) and the underlying Envoy proxies. I
Is multi-mesh here, multi istio? If so should we be explicit about that?

2021-07-29 11:35 UTC, EItanya commented on docs/content/guides/gateway/concepts.md
> +In this setup, we have a single cluster deployed with multiple gateways. The gateways can have overlap in which services they route traffic to, if desired.
```suggestion
In this setup, we have a single cluster deployed with multiple gateways. The services which these gateways route traffic to can overlap, if desired.
```

2021-07-29 11:45 UTC, EItanya commented on docs/content/guides/gateway/concepts.md
> +A VirtualGateway resource will define the [Envoy listeners](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listeners), i.e. the protocols and ports to listen on. It will also def
```suggestion
A VirtualGateway resource will define the [Envoy listeners](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listeners), i.e. the protocols and ports to listen on. It will also define which Envoy filters are attached, by allowing users to specify a [FilterChain](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/network_filter_chain) (or multiple FilterChains). It attaches to existing ingress gateway workloads via a workload selector, and specifies one or more VirtualHost configurations to configure routing rules. A single VirtualGateway can apply to multiple ingress gateway deployments across all meshes and clusters contained within a VirtualMesh. Attached Gateways will be listed in the status of the VirtualGateway. In order to perform cross-mesh routing, the Gateway Mesh and Destination Mesh _must be contained in a single VirtualMesh with federation enabled_.
```

This description is probably a bit low level, the user doesn't care about listeners or filter chains. The first bit reads more like internal documentation

2021-07-29 11:45 UTC, EItanya commented on docs/content/guides/gateway/concepts.md
> +VirtualHosts are selected by a VirtualGateway. A single VirtualHost can be selected by multiple VirtualGateways. VirtualHosts are responsible for configuring top level settings, such as domains. In a
What do you mean by "top level settings"?

2021-07-29 11:47 UTC, EItanya commented on docs/content/guides/gateway/ext_auth.md
> +title: External Authentication
These should be Authorization

2021-07-29 11:49 UTC, EItanya commented on docs/content/guides/gateway/getting_started.md
> +    bindPort: 8081
We should be binding to the service port, not the targetPort

2021-07-29 11:49 UTC, EItanya commented on docs/content/guides/gateway/ratelimiting/envoy/_index.md
> +It is already installed when doing `glooctl install gateway enterprise --license-key=...` or
gloo reference

2021-07-29 11:50 UTC, EItanya commented on docs/content/guides/gateway/ratelimiting/envoy/_index.md
> +[Envoy's rate-limit API](https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v2/config/filter/http/rate_limit/v2/rate_limit.proto).
This is v2 API, we should update with V3

2021-07-29 11:54 UTC, EItanya commented on docs/content/guides/gateway/ratelimiting/_index.md
> +kubectl logs -n gloo-mesh deploy/rate-limit -f
Call out that this will only be in agent clusters

2021-07-29 11:54 UTC, EItanya commented on docs/content/guides/gateway/ratelimiting/_index.md
> +kubectl --namespace gloo-mesh edit virtualgateways.networking.enterprise.mesh.gloo.solo.io my-gateway
Can we offer a patch command here instead, editing can definitely be confusing for the user

2021-07-29 11:57 UTC, EItanya commented on docs/content/guides/gateway/ratelimiting/crds/_index.md
> +curl -v $(mgmt-cluster url)/ratings/1
`mgmt-cluster url` can we provide a command to get this

2021-07-29 11:59 UTC, EItanya commented on docs/content/guides/gateway/ratelimiting/crds/_index.md
> +{{< highlight yaml "hl_lines=12-19" >}}
This is a shell command, should we render it that way?

2021-07-29 12:01 UTC, EItanya requested changes
Overall looks good. Rate Limit docs still have a lot of gloo edge references which need to be changed. Also, the Rate Limit docs need to ensure they reference which agent cluster to use when calling kubectl commands related to the rate limit server

2021-07-29 19:34 UTC, npolshakova commented on docs/content/guides/gateway/ratelimiting/crds/_index.md
> +curl -v $(mgmt-cluster url)/ratings/1
This is coming from the bookinfo app setup where the mgmt-cluster is cluster-1 (so this could technically change depending on how the user sets up bookinfo). I can make it BOOKINFO_INGRESS_GATEWAY_URL to make it more clear.

2021-07-29 20:50 UTC, Sodman commented on docs/content/guides/gateway/concepts.md
> +Gloo Mesh Gateway is an abstraction built on top of [Istio's ingress gateway model](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) and the underlying Envoy proxies. I
For now, yes - although I don't think we've definitively ruled out supporting other meshes for this in the long term.

2021-07-29 20:53 UTC, Sodman commented on docs/content/guides/gateway/concepts.md
> +VirtualHosts are selected by a VirtualGateway. A single VirtualHost can be selected by multiple VirtualGateways. VirtualHosts are responsible for configuring top level settings, such as domains. In a
I meant settings that can only be configured once for a VirtualHost, but will affect all child routes. Things like domain for example. Which is slightly different from setting route options on the VirtualHost, which act more like a default for child routes, but still lets the child routes overwrite them on a case by case basis if desired. Really "VirtualHost" level settings, but I'm open to suggestions on how we phrase that without using the word VirtualHost, as that's what we're trying to introduce here :)

2021-07-29 20:53 UTC, Sodman commented on docs/content/guides/gateway/ext_auth.md
> +title: External Authentication
```suggestion
title: External Authorization
```

2021-07-29 20:54 UTC, Sodman commented on docs/content/guides/gateway/ext_auth.md
> +description: Guide for configuring External authentication with Gloo Mesh Gateway
```suggestion
title: External Authorization
menuTitle: Authorization
description: Guide for configuring External Authorization with Gloo Mesh Gateway
```

2021-07-29 20:54 UTC, Sodman commented on docs/content/guides/gateway/ext_auth.md
> +{{% notice note %}} External Authentication in Gloo Mesh Gateway requires a Gloo Mesh Gateway license. {{% /notice %}}
```suggestion
{{% notice note %}} External Authorization in Gloo Mesh Gateway requires a Gloo Mesh Gateway license. {{% /notice %}}
```

2021-08-06 13:45 UTC, kdorosh submitted a review, later dismissed

2021-08-06 13:46 UTC, kdorosh commented on docs/content/guides/gateway/getting_started.md
> +  * Gloo Mesh Enterprise is [installed in relay mode and running on the `cluster-1`]({{% versioned_link_path fromRoot="/setup/install-gloo-mesh" %}})
this link is broken

2021-08-06 14:02 UTC, kdorosh approved these changes

2021-08-06 14:26 UTC, EItanya approved these changes

2021-08-06 20:40 UTC, merged