Use ingress gateway selector API
solo-io/gloo-mesh pull request #1750
Opened 2021-07-27 19:59 UTC by ryantking

2021-07-27 20:10 UTC, Sodman commented on api/enterprise/networking/v1beta1/virtual_gateway.proto
> +    repeated .discovery.mesh.gloo.solo.io.AppliedIngressGateway = 4;
This needs a field name

```suggestion
    repeated .discovery.mesh.gloo.solo.io.AppliedIngressGateway selected_gateways = 4;
```

2021-07-27 20:46 UTC, kdorosh commented on api/enterprise/networking/v1beta1/virtual_gateway.proto
> +        string bind_address = 2;
let's include the default values in the comments

2021-07-27 20:53 UTC, Sodman commented on api/enterprise/networking/v1beta1/virtual_gateway.proto
> +        string bind_address = 2;
I think the original comment also was more accurate. This is the network interface that we're _serving_ traffic on, rather than a whitelist of addresses that are allowed to connect.

2021-07-28 16:20 UTC, Sodman reviewed
LGTM! Let's hold off merging into main though until we have a GME PR that compiles with these proto changes.

2021-07-28 20:09 UTC, EItanya commented on api/common/v1/status.proto
> +message AppliedIngressGateway {
This has been changed on main: https://github.com/solo-io/gloo-mesh/commit/35183e059feb5f3d30a51f3a02a0a587f5ae71bb#diff-ca467ebeadf4904622779ddf521625907a9c42b57405e2d592a1c02ff9b39cf2

2021-07-28 20:09 UTC, EItanya commented on api/discovery/v1/mesh.proto
> +    repeated .common.mesh.gloo.solo.io.AppliedIngressGateway applied_east_west_ingress_gateways = 4;
This has also been renamed on main

2021-08-09 12:54 UTC, Sodman reviewed
The changes LGTM but can we update the existing gateway docs/examples to swap deployToIngressGateways => ingressGatewaySelectors, move bindAddress etc?

2021-08-09 20:01 UTC, Sodman commented on docs/content/guides/gateway/getting_started.md
> +  - portName: tls
I think the port name we want here is probably `http2` rather than `tls`. Here are the default ports that istio ships with when you install the default istio-ingressgateway:

![image](https://user-images.githubusercontent.com/1928125/128766721-0b3e2390-e9c1-4675-a6c5-0b353161e21d.png)

Can we also update L43 in this doc to something like "Note we're selecting the port named `http2`, which in our case corresponds to the port `8080` on our `istio-ingressgateway` service"

2021-08-10 14:28 UTC, EItanya submitted a review, later dismissed

2021-08-10 15:01 UTC, EItanya commented on install/helm/gloo-mesh-crds/crds/networking.enterprise.mesh.gloo.solo.io_v1beta1_crds.yaml
> +                    description: Specify by name the TLS port on the ingress gateway
The comment is wrong, we can fix it to be more clear, as far as portName, we can add portNumber in a follow up for sure

2021-08-10 19:19 UTC, ryantking commented on install/helm/gloo-mesh-crds/crds/networking.enterprise.mesh.gloo.solo.io_v1beta1_crds.yaml
> +            ingressGatewaySelectors:
We currently only support opening one port per service. If you want multiple ports, you'll need multiple services with the same backing workloads.

2021-08-10 19:22 UTC, ryantking commented on install/helm/gloo-mesh-crds/crds/networking.enterprise.mesh.gloo.solo.io_v1beta1_crds.yaml
> +                bindAddress:
The bind address is not yet implemented for NS traffic, but I believe when it is, the port is specified separately. What is the corresponding istio/envoy filled you're referring to?

2021-08-10 19:38 UTC, Sodman reviewed
LGTM. Let's merge once we know the GME PR is in a good spot

2021-08-11 12:30 UTC, EItanya commented on test/e2e/istio/pkg/tests/federation.go
> +					PortName: "http2",
Why did this change? We still definitely want to use the `tls` port

2021-08-11 12:31 UTC, EItanya requested changes
Switch port names

2021-08-11 12:31 UTC, EItanya commented on docs/content/guides/gateway/getting_started.md
> +  - portName: http2
Why are we defaulting to `http2` for these examples, we should switch to `http` as these examples are using plaintext

2021-08-11 14:44 UTC, EItanya commented on api/common/v1/status.proto
> +    .core.skv2.solo.io.ClusterObjectRef destination_ref = 1;
Why did this become a ClusterObjectRef since destinations are always local to the management-cluster?

2021-08-11 18:13 UTC, EItanya approved these changes

2021-08-11 19:23 UTC, merged

2021-08-12 13:06 UTC, Sodman commented on docs/content/guides/gateway/getting_started.md
> +  - portName: http2
We spoke offline about this - just to close the loop: Istio's default installation includes an istio-ingressgateway that uses a Service which names the port `http2`. Our selector is based on this Service's port's name, which is why we use http2 here. The actual protocol that will be used by the Envoy Listener is determined by whether the listener is HTTP or TCP, and whether SSLConfig is set (HTTPS/TLS).